seed: 2568
img_size: 128
use_float16: True
checkpoint: checkpoint.pt
model:
  in_ch: 3
  out_ch: 3
  model_ch: 128 # 256
  timesteps: 1000
  time_emb_dim: 512
  num_resblock: 3
  ch_mult: [1, 1, 1, 3, 3]
  attn_ds: [4, 8, 16]
  num_heads: 4
  dropout_p: 0.1

diffusion:
  num_timesteps: 1000
  schedule_name: cosine
  use_posterior_variance: False
  clip_denoised: False

training:
  max_step: 200_000
  root: /scratch/ravnavg.scee.iitmandi/CelebAMask-HQ/CelebA-HQ-img # /scratch/ravnavg.scee.iitmandi/14-celebrity-faces-dataset/data # /Users/raunavghosh/Documents/code_projects/14-celebrity-faces-dataset/data
  batch_size: 128
  mini_batch_size: 16
  ema_rate: 0.9999

optimizer:
  lr: 5e-5
  betas: [0.9, 0.995]
  amsgrad: True
